//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        public string isbn { get; set; }
        public string bookName { get; set; }
        public Nullable<int> publisherID { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> count { get; set; }
        public string pic { get; set; }
        public string description { get; set; }
    }
}
